name: Build Mod Menu APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Gradle and Java 8
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '6.1.1'
        java-version: '8'

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ModMenu-APK
        path: app/build/outputs/apk/debug/app-debug.apk
